apiVersion: v1
kind: Service
metadata:
  name: travel-frontend-svc
  namespace: travel-frontend
spec:
  selector:
    app: travel-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
